---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
  run_list:
  - recipe[rackspace_apt]
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.4_chef-provisionerless.box
- name: debian-7.2.0
  driver_config:
    box: opscode-debian-7.2.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
  run_list:
  - recipe[rackspace_apt]

suites:
  - name: rackspace_holland-mysqldump
    run_list:
      - recipe[rackspace_mysql::server]
      - recipe[rackspace_holland::mysqldump]
  - name: holland_test
    run_list:
      - recipe[rackspace_mysql::server]
      - recipe[holland_test::mysqldump]
